// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Password  string
}
